// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Stargate.API.Data;
using System;

namespace Stargate.API.Migrations
{
    [DbContext(typeof(StargateContext))]
    [Migration("20171111014747_AddFileSizeBytesToFiles")]
    partial class AddFileSizeBytesToFiles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Stargate.API.Data.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("ExternalUri");

                    b.Property<string>("FileExtension");

                    b.Property<string>("FileName");

                    b.Property<long>("FileSizeBytes");

                    b.Property<string>("ShortUri");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
